/**
 * azure.ts — Azure AD SSO deep-link flow for the mobile client.
 *
 * 1. The user taps "Sign in with Microsoft" on the LoginScreen.
 * 2. We call `GET /api/auth/azure/start` to get an authorization URL.
 *    The server mints PKCE state + nonce, persists them, and returns
 *    the URL to redirect to.
 * 3. We open the URL in the system browser via `expo-linking`.
 * 4. After consent, Azure redirects to `nmc://auth?code=...&state=...`.
 * 5. We call `GET /api/auth/azure/callback.json?code&state` to
 *    exchange the code for a JWT and profile, then persist via
 *    `saveSession()`. (The browser-redirect variant of the callback
 *    is used by the web SPA; the `.json` variant returns JSON for
 *    native clients.)
 *
 * Requires server env: `AZURE_TENANT_ID`, `AZURE_CLIENT_ID`,
 * `AZURE_REDIRECT_URI`. The redirect URI must be the deep-link URL
 * generated by `azureRedirectUri` below (or its equivalent on the
 * configured tenant).
 */
import * as Linking from 'expo-linking';
import { api } from './api';
import { saveSession, type StoredSession } from './session';

const REDIRECT_SCHEME = 'nmc';
const REDIRECT_PATH = 'auth';

export const azureRedirectUri = Linking.createURL(REDIRECT_PATH, {
  scheme: REDIRECT_SCHEME,
});

interface AzureCallbackResponse {
  token: string;
  user: { id: number | string; email: string; username?: string; role?: string };
  profile: { id: string; email: string; name?: string };
}

export async function startAzureLogin(): Promise<void> {
  // `api.azureStart()` resolves to `{ url, state }`. Any 503 from the
  // server surfaces here as a thrown error — callers should `try/catch`.
  const start = await api.azureStart();
  await Linking.openURL(start.url);
}

/**
 * Complete the Azure AD SSO exchange after the system browser
 * redirects back into the app via the `nmc://auth` deep link.
 *
 * The deep-link URL is expected to look like:
 *   nmc://auth?code=<id_token>&state=<pkce_state>
 */
export async function completeAzureLoginFromUrl(
  url: string,
): Promise<StoredSession> {
  const { queryParams } = Linking.parse(url);
  const code = typeof queryParams?.code === 'string' ? queryParams.code : null;
  const state = typeof queryParams?.state === 'string' ? queryParams.state : null;
  if (!code || !state) {
    throw new Error('Azure callback URL missing code or state.');
  }
  // The api-client doesn't expose a dedicated azureCallback() wrapper;
  // hit the raw JSON endpoint via the base URL the client was built with.
  const base = api.baseUrl.replace(/\/$/, '');
  const res = await fetch(
    `${base}/api/auth/azure/callback.json?code=${encodeURIComponent(code)}&state=${encodeURIComponent(state)}`,
  );
  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as { error?: string; detail?: string };
    throw new Error(body.error ?? `Azure callback failed (HTTP ${res.status})`);
  }
  const payload = (await res.json()) as AzureCallbackResponse;
  const session: StoredSession = {
    accessToken: payload.token,
    refreshToken: '', // server doesn't return one for Azure flows; the access token is refreshed via /api/auth/refresh
    user: {
      id: String(payload.user.id),
      email: payload.profile.email,
      name: payload.profile.name,
    },
  };
  await saveSession(session);
  return session;
}